language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3
# A hack required to enable 3.7 until Travis adds proper support for 3.7:
# https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
  - pip install flake8
  - pip install coverage
  - pip install coveralls
  - pip install mock
  - pip install nose
script:
  - nosetests notify_send_tests.py --with-coverage --cover-package=notify_send --cover-erase
  - flake8 --ignore=E402,E501 notify_send.py notify_send_tests.py
after_success:
  - coveralls
